[env:native]
platform = native
build_flags =
    -std=c++17
    -DCRYPTO_LITTLE_ENDIAN=1
    -Wall
    -Wextra
    -Iinclude
    -Isrc
    -Icli
extra_scripts =
    pre:bin/set_progname.py
    pre:bin/configure_berry.py
lib_deps =
    rweather/Crypto@^0.4.0
    https://github.com/berry-lang/berry/archive/7af8289b95e937e22a553c1688b563841c53247b.zip
lib_ldf_mode = deep+
lib_compat_mode = off
build_src_filter =
    +<../src/>
    +<../cli/>
test_build_src = true
test_framework = unity
